#include "STD_TYPES.h"
#include "BIT_MATH.h"

/* Your Drivers */
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "TIM_interface.h"

#define TRIGGER_PORT     GPIOB
#define TRIGGER_PIN      PIN0

#define PWM_TIMER        TIM3
#define PWM_CHANNEL      TIM_CHANNEL_1

int main(void)
{
    /* ================= Clock Init ================= */

    MRCC_voidInitSystemClock();

    MRCC_voidEnablePeripheralClock(RCC_APB2, RCC_IOPA);
    MRCC_voidEnablePeripheralClock(RCC_APB2, RCC_IOPB);
    MRCC_voidEnablePeripheralClock(RCC_APB1, RCC_TIM3);

    /* ================= Trigger Pin ================= */

    MGPIO_voidSetPinDirection(TRIGGER_PORT, TRIGGER_PIN, GPIO_OUTPUT_2MHZ_PP);

    /* Trigger = HIGH */
    MGPIO_voidSetPinValue(TRIGGER_PORT, TRIGGER_PIN, GPIO_HIGH);

    /* ================= PWM Pin ================= */

    /*
        PA6 = TIM3_CH1
        Configure it as Alternate Function Push Pull
    */
    MGPIO_voidSetPinDirection(GPIOA, PIN6, GPIO_OUTPUT_2MHZ_AFPP);

    /* ================= PWM Init ================= */

    /*
        Example:
        Timer clock = 72 MHz
        PSC = 71  -> timer tick = 1 MHz
        ARR = 999 -> PWM frequency = 1 kHz
        CCR = 250 -> Duty cycle = 25%
    */

    MTIM_voidPWMInit(PWM_TIMER, PWM_CHANNEL);

    MTIM_voidSetPrescaler(PWM_TIMER, 71);
    MTIM_voidSetAutoReload(PWM_TIMER, 999);
    MTIM_voidSetCompareValue(PWM_TIMER, PWM_CHANNEL, 250);

    MTIM_voidStart(PWM_TIMER);

    while (1)
    {
        /*
            PWM is generated by hardware.
            Nothing needed here.
        */
    }
}